### ISSUE TITLE
已删除的任务(定时任务)在指定时间仍会运行

### ISSUE THREAD

**Issue by misdake** [Tuisku-L/Ask.MrTask.Tools#2]
用户名同github，id: b38f3afe-7324-4c0b-a11b-40379fd64eed

可能的复现过程：添加脚本文件，新建脚本，新建任务，删除脚本。
新建的任务是整小时运行的。在删除脚本后，任务在任务列表中不可见，但是仍然会在整点运行。

图中已删除的任务是上述任务，在每小时的0分运行。
![issue](https://user-images.githubusercontent.com/3875842/79114453-ec959500-7db5-11ea-8287-4e8032b93e7f.png)

**Comment by Woo0ood** [comment]
已修复此 Bug，感谢反馈~
