### ISSUE TITLE
如何安装python 库

### ISSUE THREAD

**Issue by nedtang** [Tuisku-L/Ask.MrTask.Tools#4]
你好，如何在我执行任务之前安装库

**Comment by Woo0ood** [comment]
### 请使用自定义脚本

### Example

#### Python 示例

`test.py` 是使用 `Pyhton 3.x` 的脚本，并且使用到了 `requests` 模块，则自定义脚本为：

```shell
pip3 install requests --user
python $HOME/test.py
```

请记住，在使用 `pip`/`pip3` 的时候**一定**要带上 `--user` 参数
